### PR TITLE
feat: stall started / ended event hooks

### PR DESCRIPTION
**Pull request by joornby-angel**
Added Stall Started/Stopped event hooks.

### CODE REVIEW

**Review by rolandkakonyi — CHANGES_REQUESTED** [review]
Changes and manual testing look good but please also add an `onEvent` callback to `PlayerView` in `BasicPlayback` example to showcase the usage.

Like:
```ts
      <PlayerView
        player={player}
        style={styles.player}
        ... // redacted
        onStallStarted={onEvent}
        onStallEnded={onEvent}
      />
```

**Review by matamegger — APPROVED** [review]
Looks good once @rolandkakonyi comment is resolved.

**Comment by joornby-angel** [comment]
@rolandkakonyi I added the event callbacks in the BasicPlayback.tsx file.  Let me know if there's anything else you'd like me to add.

**Review by rolandkakonyi — APPROVED** [review]
Changes look good!
No further changes needed!

**Review by pogist — APPROVED** [review]

**Pull request merged**
